// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfwgzojqlamphfvnttcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmd2d6b2pxbGFtcGhmdm50dGNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3OTI1NjUsImV4cCI6MjA2MDM2ODU2NX0.Fs5qgvV1BlrgXK7NvlvTY2f1X1Lj0rrQPGcTVmvMSEY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);